### ISSUE TITLE
PushConsumer 模式下 启动报错

### ISSUE THREAD

**Issue by light-x** [apache/rocketmq-client-python#110]
1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
 ``` consumer = PushConsumer(consumer_group_id)
     consumer.set_name_server_address(name_srv_addr)
     consumer.subscribe(topic, callback)
     consumer.start()
     time.sleep(10)
     def call_back(msg):
    try:
        if len(msg) == 0:
            logger.info('invalid data')
            return ConsumeStatus.CONSUME_SUCCESS
        else:
            logger.info('RECONSUME_LATER ')
            return ConsumeStatus.RECONSUME_LATER
    except Exception as e:
        logger.error(e)
        return ConsumeStatus.RECONSUME_LATER
 ```

- What did you expect to see?
   正常消费消息
- What did you see instead?
   ```
  Traceback (most recent call last):
  Traceback (most recent call last):
    File "_ctypes/callbacks.c", line 234, in 'calling callback function'
    File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  TypeError: 'managedbuffer' object is not callable
  Traceback (most recent call last):
  FATAL: exception not rethrown
   ```

2. Please tell us about your environment:

 - What is your OS?
    CentOS Linux release 7.2 (Final)

 - What is your client version?
   rocketmq-client-python (2.0.0)
   rocketmq-client-cpp-2.2.0
   python:Python 3.6.8

- /root/logs/rocketmq-cpp log
   ```
        [2021-Mar-02 19:01:35.219898](info):new pull callback for mq:MessageQueue [topic=portal_std_water, brokerName=mq-broker1, queueId=0][getAsyncPullCallBack:789]
    [2021-Mar-02 19:01:35.219958](info):new pull callback for mq:MessageQueue [topic=portal_std_water, brokerName=mq-broker1, queueId=1][getAsyncPullCallBack:789]
    [2021-Mar-02 19:01:35.220076](info):new pull callback for mq:MessageQueue [topic=portal_std_water, brokerName=mq-broker1, queueId=2][getAsyncPullCallBack:789]
    [2021-Mar-02 19:01:35.220166](info):new pull callback for mq:MessageQueue [topic=portal_std_water, brokerName=mq-broker1, queueId=3][getAsyncPullCallBack:789]
    [2021-Mar-02 19:01:35.220230](info):new pull callback for mq:MessageQueue [topic=portal_std_water, brokerName=mq-broker1, queueId=4][getAsyncPullCallBack:789]
    [2021-Mar-02 19:01:35.220276](info):new pull callback for mq:MessageQueue [topic=portal_std_water, brokerName=mq-broker1, queueId=5][getAsyncPullCallBack:789]
    [2021-Mar-02 19:01:35.220455](info):new pull callback for mq:MessageQueue [topic=portal_std_water, brokerName=mq-broker1, queueId=6][getAsyncPullCallBack:789]
    [2021-Mar-02 19:01:35.220555](info):new pull callback for mq:MessageQueue [topic=portal_std_water, brokerName=mq-broker1, queueId=7][getAsyncPullCallBack:789]
    [2021-Mar-02 19:01:35.220521](info):clientFactory:127.0.0.1@24179#DEFAULT start consumer_timerOperation[consumer_timerOperation:906]
    [2021-Mar-02 19:01:35.223155](error):Consumer's code is buggy. Un-caught exception raised[ConsumeRequest:221]
   ```
 - What is your RocketMQ version?
    
 -

**Comment by francisoliverlee** [comment]
give a try with py2
